### ISSUE TITLE
Do you want to participate the TAAI computer go tournament?

### ISSUE THREAD

**Issue by CGLemon** [meiji163/bokego#20]
TAAI tournament will be held on 11/20. Registration deadlines is 11/12. 

The rule is here
https://www.tcga.tw/taai2021/attachment/rules/Go_9x9/9X9.txt

The game platform is KGS. To connect the server by kgsGtp.jar , you can download it here
https://www.gokgs.com/download.jsp

Registration side is here
https://www.tcga.tw/taai2021/en/

Finally, you may participate the game by google meet or other applications.

**Comment by meiji163** [comment]
Sure, it sounds fun!

**Comment by CGLemon** [comment]
There are some information you may want to get.

1. What's TAAI compute game tournament?
TAAI compute game tournament is same as ICGA compute game tournament. Many compute games will be held. The 9x9 go is one of them.

2. How to pay the fee?
Actually, I don't know about that. They collect the fees at the tournament. But feel free participate the game. You may pay the fee after the game. I will help you to ask it on that day.

3. How to use the kgsGtp?
First, go to here to register a new account. 
https://www.gokgs.com/register/index.html
Second, follow above kgsGtp document.
http://www.weddslist.com/kgs/how/kgsGtp.html

4. What minimal GTP instructions does boke need to support?
Boke already implement almost all basic GTP instructions. So you don't need to change anything. But there are some optional instructions you may implement. They are "time_settings", "time_left" and "final_status_list dead/alive".
Because each side will get only 10 min thinking time, "time_settings" and "time_left" can tell  engine remaining time. If you sure that boke can play whole game under 10 min( including server lag time ), the boke doesn't need to support them.
When the game is end,  "final_status_list dead/alive" help the server to remove the dead strings. But in my experience, most game were end by resigning. This instruction is not important.

5. What time the game will be held?
The tournament will start at 8:30 am, 11/20 in Taiwan( 8:30 pm, 11/19 in New York ). But we started the game until all player were ready(around 10:00 am ~ 11:00 am) in the past tournaments. The starting time is not fixed.  We will discuss the time later.

You may go to registration side to get more information.

**Comment by CGLemon** [comment]
Here are the kgsGtp config file used in TAAI.

    name=<account name>
    password=<account password>
    room=Computer Go
    mode=custom
    
    rules=chinese
    rules.boardSize=9
    rules.time=10:00
    
    opponent=<opponent’s  name>
    
    undo=f
    reconnect=t
    verbose=t
    
    engine=<engine path and arguments>
