### ISSUE TITLE
2022 TCGA Computer Go Tournament is coming!

### ISSUE THREAD

**Issue by CGLemon** [meiji163/bokego#21]
TCGA tournament is same as TAAI. I want to invite you again. The computer Go game tournament will be held on 5/14. Registration deadlines is 5/7 in Taiwan. 

The rule is very similar to the Tromp-Taylor rules, the detail is here

    Board Size 9
    Time Control is 10 minutes Sudden Death.
    Area Scoring(chinese-rule).
    No suicide allowed.
    Komi 7
    Positional Superko is used.

The game platform is [KGS](https://www.gokgs.com/). To connect the server by [kgsGtp.jar](https://www.gokgs.com/download.jsp).

Registration side is [here](https://tcga.tw/tournament2022/en/)

Others, you may watch the post issue #20 .

**Comment by meiji163** [comment]
I will not miss it!

**Comment by CGLemon** [comment]
Do you want to participate 19x19 Go game? Becacue I want to resurrect the 19x19 Go game on TCGA.

**Comment by meiji163** [comment]
Hi @CGLemon, I don't know if I can make a bot in time for 19x19 TCGA. I can try!

**Comment by CGLemon** [comment]
The dead time is gone, but you still can register your program. Please do it quickly because we will decide the schedule current day. Hope you may participate with us! Thanks.
